# Generated by Django 4.2.14 on 2024-07-22 16:10

import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import gymlog.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("weight_reps", "Weight Reps"),
                            ("reps_only", "Reps Only"),
                            ("weighted_bodyweight", "Weighted Bodyweight"),
                            ("assisted_bodyweight", "Assisted Bodyweight"),
                            ("duration", "Duration"),
                            ("weight_duration", "Weight & Duration"),
                            ("distance_duration", "Distance Duration"),
                            ("weight_distance", "Weight & Distance"),
                        ],
                        max_length=255,
                        verbose_name="Exercise Type",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("barbell", "Barbell"),
                            ("dumbbell", "Dumbbell"),
                            ("kettlebell", "Kettlebell"),
                            ("machine", "Machine"),
                            ("plate", "Plate"),
                            ("resistance_band", "Resistance Band"),
                            ("suspension", "Suspension"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                        verbose_name="Equipment",
                    ),
                ),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("legs", "Legs"),
                            ("shoulders", "Shoulders"),
                            ("core", "Core"),
                            ("cardio", "Cardio"),
                        ],
                        max_length=255,
                        verbose_name="Primary muscle group",
                    ),
                ),
                (
                    "other_muscles",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("biceps", "Biceps"),
                            ("triceps", "Triceps"),
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("legs", "Legs"),
                            ("shoulders", "Shoulders"),
                            ("core", "Core"),
                            ("cardio", "Cardio"),
                        ],
                        max_length=255,
                        verbose_name="Other Muscles",
                    ),
                ),
                (
                    "small_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exercise_small_images/",
                        verbose_name="Small Image",
                    ),
                ),
                (
                    "large_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exercise_large_images/",
                        verbose_name="Large Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
                "db_table": "exercises",
            },
        ),
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine",
                "verbose_name_plural": "Routines",
                "db_table": "routines",
            },
        ),
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "rest_timer",
                    models.DurationField(
                        blank=True,
                        default="00:01:00",
                        null=True,
                        verbose_name="Rest Timer",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.exercise"
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_exercises",
                        to="gym.routine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Exercise",
                "verbose_name_plural": "Routine Exercises",
                "db_table": "routine_exercises",
                "ordering": ["order"],
                "unique_together": {("routine", "exercise")},
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(blank=True, null=True, verbose_name="start"),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="end"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="Volume"
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workouts",
                        to="gym.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
                "db_table": "workouts",
                "ordering": ["-start"],
                "unique_together": {("user", "routine")},
            },
        ),
        migrations.CreateModel(
            name="ExerciseLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.exercise"
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_logs",
                        to="gym.workout",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercise Log",
                "verbose_name_plural": "Exercise Logs",
                "db_table": "exercise_logs",
                "ordering": ["order"],
                "unique_together": {("workout", "order")},
            },
        ),
        migrations.CreateModel(
            name="SetLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("weight", models.FloatField(verbose_name="Weight")),
                ("reps", models.PositiveIntegerField(verbose_name="Reps")),
                (
                    "exercise_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_logs",
                        to="gym.exerciselog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set Log",
                "verbose_name_plural": "Set Logs",
                "db_table": "set_logs",
                "ordering": ["order"],
                "unique_together": {("exercise_log", "order")},
            },
        ),
        migrations.CreateModel(
            name="RoutineSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=gymlog.mixins.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                ("weight", models.FloatField(verbose_name="Weight")),
                ("reps", models.PositiveIntegerField(verbose_name="Reps")),
                (
                    "routine_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routine_sets",
                        to="gym.routineexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Routine Set",
                "verbose_name_plural": "Routine Sets",
                "db_table": "routine_sets",
                "ordering": ["order"],
                "unique_together": {("routine_exercise", "order")},
            },
        ),
    ]
