# Generated by Django 4.2.14 on 2024-07-23 15:25

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0002_exercise_name_en_exercise_name_es_exercise_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("weight_reps", "Weight Reps"),
                    ("reps_only", "Reps Only"),
                    ("weighted_bodyweight", "Weighted Bodyweight"),
                    ("assisted_bodyweight", "Assisted Bodyweight"),
                    ("duration", "Duration"),
                    ("weight_duration", "Weight & Duration"),
                    ("distance_duration", "Distance Duration"),
                    ("weight_distance", "Weight & Distance"),
                    ("bodyweight_reps", "Bodyweight Reps"),
                    ("bodyweight_assisted_reps", "Bodyweight Assisted Reps"),
                    ("short_distance_weight", "Short Distance Weight"),
                ],
                max_length=255,
                verbose_name="Exercise Type",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="other_muscles",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("abdominals", "Abdominals"),
                    ("abductors", "Abductors"),
                    ("adductors", "Adductors"),
                    ("biceps", "Biceps"),
                    ("lower_back", "Lower Back"),
                    ("upper_back", "Upper Back"),
                    ("cardio", "Cardio"),
                    ("chest", "Chest"),
                    ("calves", "Calves"),
                    ("forearms", "Forearms"),
                    ("glutes", "Glutes"),
                    ("hamstrings", "Hamstrings"),
                    ("lats", "Lats"),
                    ("quadriceps", "Quadriceps"),
                    ("shoulders", "Shoulders"),
                    ("triceps", "Triceps"),
                    ("traps", "Traps"),
                    ("neck", "Neck"),
                    ("full_body", "Full Body"),
                    ("other", "Other"),
                ],
                max_length=255,
                verbose_name="Other Muscles",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="primary_muscle_group",
            field=models.CharField(
                choices=[
                    ("abdominals", "Abdominals"),
                    ("abductors", "Abductors"),
                    ("adductors", "Adductors"),
                    ("biceps", "Biceps"),
                    ("lower_back", "Lower Back"),
                    ("upper_back", "Upper Back"),
                    ("cardio", "Cardio"),
                    ("chest", "Chest"),
                    ("calves", "Calves"),
                    ("forearms", "Forearms"),
                    ("glutes", "Glutes"),
                    ("hamstrings", "Hamstrings"),
                    ("lats", "Lats"),
                    ("quadriceps", "Quadriceps"),
                    ("shoulders", "Shoulders"),
                    ("triceps", "Triceps"),
                    ("traps", "Traps"),
                    ("neck", "Neck"),
                    ("full_body", "Full Body"),
                    ("other", "Other"),
                ],
                max_length=255,
                verbose_name="Primary muscle group",
            ),
        ),
    ]
