# Generated by Django 4.2.14 on 2024-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_alter_exercise_exercise_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workout",
            options={
                "ordering": ["-created"],
                "verbose_name": "Workout",
                "verbose_name_plural": "Workouts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="workout",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="setlog",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.RemoveField(
            model_name="workout",
            name="start",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="user",
        ),
    ]
