# Generated by Django 4.2.14 on 2024-07-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("ru", "Russian"), ("es", "Spanish")],
                max_length=10,
                verbose_name="Preferred language",
            ),
        ),
    ]
